/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Fibonacci.java
 *
 * Created on 29/05/2010, 22:28:37
 */

package lista_4;

import javax.swing.JOptionPane;

/**
 *
 * @author maykon
 */
public class Fibonacci extends javax.swing.JFrame {

    /** Creates new form Fibonacci */
    public Fibonacci() {
        initComponents();
        this.setTitle("Fibonacci");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnCalcular = new javax.swing.JButton();
        jLblFibonacci = new javax.swing.JLabel();
        jLblQtdSeries = new javax.swing.JLabel();
        jTxtQtdSeries = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(lista_4.Lista_4App.class).getContext().getResourceMap(Fibonacci.class);
        jBtnCalcular.setText(resourceMap.getString("jBtnCalcular.text")); // NOI18N
        jBtnCalcular.setName("jBtnCalcular"); // NOI18N
        jBtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcularActionPerformed(evt);
            }
        });

        jLblFibonacci.setText(resourceMap.getString("jLblFibonacci.text")); // NOI18N
        jLblFibonacci.setName("jLblFibonacci"); // NOI18N

        jLblQtdSeries.setText(resourceMap.getString("jLblQtdSeries.text")); // NOI18N
        jLblQtdSeries.setName("jLblQtdSeries"); // NOI18N

        jTxtQtdSeries.setText(resourceMap.getString("jTxtQtdSeries.text")); // NOI18N
        jTxtQtdSeries.setName("jTxtQtdSeries"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblFibonacci, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtQtdSeries, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(jBtnCalcular))
                            .addComponent(jLblQtdSeries))
                        .addGap(323, 323, 323))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblQtdSeries)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtQtdSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCalcular))
                .addGap(18, 18, 18)
                .addComponent(jLblFibonacci, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcularActionPerformed
        // TODO add your handling code here:
        try {
            int qtd = Integer.parseInt(this.jTxtQtdSeries.getText())+1;
            int[] sequencia = new int[qtd+1];
            sequencia[0] = 0;
            sequencia[1] = 1;

            StringBuffer sb = new StringBuffer();
            for (int i=2; i<sequencia.length; i++) {
                sequencia[i] = sequencia[i -1] + sequencia[i - 2];
                if (i==(sequencia.length-1)) {
                    sb.append(" " + String.valueOf(sequencia[i]));
                } else {
                    sb.append(" " + String.valueOf(sequencia[i]) + ", ");
                }
            }
            this.jLblFibonacci.setText(sb.toString());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(jBtnCalcular, "Por favor digite um número inteiro em 'Qtd. séries'!", "Erro", 1);
            System.out.println(e.getMessage());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(jBtnCalcular, "Não foi possível efetuar o cálculo.", "Erro", 0);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jBtnCalcularActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fibonacci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCalcular;
    private javax.swing.JLabel jLblFibonacci;
    private javax.swing.JLabel jLblQtdSeries;
    private javax.swing.JTextField jTxtQtdSeries;
    // End of variables declaration//GEN-END:variables

}
