/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Fibonacci.java
 *
 * Created on 29/05/2010, 22:28:37
 */

package lista_4;

import javax.swing.JOptionPane;

/**
 *
 * @author maykon
 */
public class FizzBuzz extends javax.swing.JFrame {

    /** Creates new form Fibonacci */
    public FizzBuzz() {
        initComponents();
        this.setTitle("FizzBuzz");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnOK = new javax.swing.JButton();
        jLblResultado = new javax.swing.JLabel();
        jLbNumero = new javax.swing.JLabel();
        jTxtNumero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(lista_4.Lista_4App.class).getContext().getResourceMap(FizzBuzz.class);
        jBtnOK.setText(resourceMap.getString("jBtnOK.text")); // NOI18N
        jBtnOK.setName("jBtnOK"); // NOI18N
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });

        jLblResultado.setText(resourceMap.getString("jLblResultado.text")); // NOI18N
        jLblResultado.setName("jLblResultado"); // NOI18N

        jLbNumero.setText(resourceMap.getString("jLbNumero.text")); // NOI18N
        jLbNumero.setName("jLbNumero"); // NOI18N

        jTxtNumero.setText(resourceMap.getString("jTxtNumero.text")); // NOI18N
        jTxtNumero.setName("jTxtNumero"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnOK))
                    .addComponent(jLblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbNumero)
                    .addComponent(jTxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnOK))
                .addGap(18, 18, 18)
                .addComponent(jLblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed
        // TODO add your handling code here:
        try {
            int num = Integer.parseInt(this.jTxtNumero.getText());
            String resultado  = new String();
            if (((num % 5) == 0) && ((num % 7) == 0)) {
                resultado = "fizzbuzz";
            } else if ((num % 5) == 0) {
                resultado = "fizz";
            } else if ((num % 7) == 0) {
                resultado = "buzz";
            }
            jLblResultado.setText(resultado);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(jBtnOK, "Não foi possível processar.", "Erro", 0);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jBtnOKActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FizzBuzz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnOK;
    private javax.swing.JLabel jLbNumero;
    private javax.swing.JLabel jLblResultado;
    private javax.swing.JTextField jTxtNumero;
    // End of variables declaration//GEN-END:variables

}
