/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Fibonacci.java
 *
 * Created on 29/05/2010, 22:28:37
 */

package lista_4;

import javax.swing.JOptionPane;

/**
 *
 * @author maykon
 */
public class InverteFrase extends javax.swing.JFrame {

    /** Creates new form Fibonacci */
    public InverteFrase() {
        initComponents();
        this.setTitle("Inverte frase");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnInverter = new javax.swing.JButton();
        jLblFraseInvertida = new javax.swing.JLabel();
        jLblFrase = new javax.swing.JLabel();
        jTxtFrase = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(lista_4.Lista_4App.class).getContext().getResourceMap(InverteFrase.class);
        jBtnInverter.setText(resourceMap.getString("jBtnInverter.text")); // NOI18N
        jBtnInverter.setName("jBtnInverter"); // NOI18N
        jBtnInverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInverterActionPerformed(evt);
            }
        });

        jLblFraseInvertida.setText(resourceMap.getString("jLblFraseInvertida.text")); // NOI18N
        jLblFraseInvertida.setName("jLblFraseInvertida"); // NOI18N

        jLblFrase.setText(resourceMap.getString("jLblFrase.text")); // NOI18N
        jLblFrase.setName("jLblFrase"); // NOI18N

        jTxtFrase.setText(resourceMap.getString("jTxtFrase.text")); // NOI18N
        jTxtFrase.setName("jTxtFrase"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblFraseInvertida, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblFrase)
                                .addGap(249, 249, 249))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtFrase, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jBtnInverter)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblFrase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnInverter))
                .addGap(18, 18, 18)
                .addComponent(jLblFraseInvertida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnInverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInverterActionPerformed
        // TODO add your handling code here:
        try {
            StringBuffer sb = new StringBuffer(this.jTxtFrase.getText());
            this.jLblFraseInvertida.setText(sb.reverse().toString());
        } catch(Exception e) {
            JOptionPane.showMessageDialog(jBtnInverter, "Não foi possível inverter a frase.", "Erro", 0);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jBtnInverterActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InverteFrase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnInverter;
    private javax.swing.JLabel jLblFrase;
    private javax.swing.JLabel jLblFraseInvertida;
    private javax.swing.JTextField jTxtFrase;
    // End of variables declaration//GEN-END:variables

}
